### PR TITLE
SWITCHYARD-2972 - adding operation selector for rest binding UI

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by bfitzpat** [comment]
@lhein or @apupier if you get a chance, can you take a look at this fix? all I'm doing is adding an operation selector drop-down so users can specify one operation on the interface if there is more than one available. It's the same approach we have used on other bindings - it was just not enabled on this particular binding for some reason.

**Comment by bfitzpat** [comment]
@apupier there is no test associated with this from the development side, but hopefully @apodhrad and his team of QE wizards can create one in RedDeer to ensure that this is tested on their side. We still need to find a better way to test the UI elements for SY on the unit test side of things.

**Comment by apodhrad** [comment]
please do not merge this PR

**Comment by bfitzpat** [comment]
@apodhrad let's continue the conversation on the JIRA

**Comment by bfitzpat** [comment]
Closing this request. Will go back to just updating validation.

**Pull request closed without merging**
