### PR TITLE
SWITCHYARD-2976 - update to org.slf4j reference

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by bfitzpat** [comment]
@lhein or @apupier can you give this a quick once-over - it's for a RPM issue that doesn't show up elsewhere, so was requested from the Dev Tools team.

**Comment by nickboldt** [comment]
+1, looks reasonable.

**Comment by bfitzpat** [comment]
We just removed the slf4j reference all together. Everything builds. All tests pass. Smoke test seems ok.

**Comment by bfitzpat** [comment]
Which is apparently exactly what #644 did. Go figure. Thanks Nick.

**Comment by nickboldt** [comment]
cool. so it's approved. can we merge it?

**Pull request merged**
