### PR TITLE
SWITCHYARD-2907 - fix for configuration version change facet problem

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by apupier** [comment]
I don't understand how it is working.
The workingCopy seems not used as a dispose is called just assigning it.
Not using the workingcopy woudl mean that we modify a workingcopy, then modify directly the project and then the reapplying the working copy modification? Shouldn't be lead to some conflicts?
Maybe Fred will be better to review this PR.

**Comment by bfitzpat** [comment]
The issue was that we were getting the maven project from the project cache but it hadn't been populated yet, so when we tried to remove the test folders it wasn't getting an up-to-date maven project in memory based on what was in the workspace. But I see what you mean about the working copy not even being used now.

**Comment by bfitzpat** [comment]
Considering that we add capabilities behind the scenes when users drag components from the palette onto the canvas and I'm seeing the same issue (with the NPE in getChildrenNotInDiagram)
there - this is definitely a problem. The fix takes care of the facet issue reported, but I'm still seeing the original problem. Investigating further.

**Comment by bfitzpat** [comment]
Turns out that I went a step too far on the first go-round of the change. We're still using the working copy of the project, but instead of forcing the projectFacade to re-create itself we now just use the facet stashed in the working copy and ensure (by passing the monitor) that it gets reloaded into the cache. This is a simpler solution, which actually works better with the existing code - I found several issues with shoehorning in the earlier change. That fixes the facet issues we were having when we updated the capabilities or changed the configuration version and all is well with the world. 

Also, I updated to check for the npe on the SCADiagramUpdateCompositeFeature.getChildrenNotInDiagram problem. That now is happier as well in local testing. 

Will wait for the PR build to pass, but this should resolve both issues seen with 2907

**Comment by bfitzpat** [comment]
Closing this PR until I get the underlying issues with 2907 and 2956 resolved.

**Pull request closed without merging**
