### PR TITLE
FUSETOOLS-2018 - handle refresh case where adding/removing capabilities

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by lhein** [comment]
So you put back the refresh which seemed to have caused other issues. Are those gone now?

**Comment by lhein** [comment]
did not meant to close it...hit the wrong button

**Comment by bfitzpat** [comment]
refresh in this case is just for the features file, not the project itself - the new method does the update maven project on the whole project.

**Comment by bfitzpat** [comment]
so this is a different type of refresh than we hit before. (it was there before in fact)

**Comment by lhein** [comment]
+1 if test build succeeds

**Comment by bfitzpat** [comment]
Build fails because of the validation issues we're fighting with FUSETOOLS-2092

**Comment by bfitzpat** [comment]
Have the timeout issues solved. Fixing a couple of checkstyle issues now.

**Comment by bfitzpat** [comment]
Success!

**Pull request merged**
