### PR TITLE
SWITCHYARD-2391: Create log4j.xml file in src/test/resources when

### PR DESCRIPTION
**Pull request by bfitzpat**
creating new SwitchYard projects 

Task-Url: https://issues.jboss.org/browse/SWITCHYARD-2391

### CODE REVIEW

**Comment by rcernich** [comment]
@bfitzpat there are some checkstyle errors which require a bit more than a simple fix.  Please update the PR.

**Comment by bfitzpat** [comment]
Working on it.

**Comment by bfitzpat** [comment]
Fixed and updated. Sorry for the trouble.

**Comment by bfitzpat** [comment]
There was a typo - two forward slashes in the closing XML tag. It's been fixed and updated.

**Comment by bfitzpat** [comment]
All tests passed on my linux box after the latest update.

**Pull request merged**
