### PR TITLE
Provide Project configuration files

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by bfitzpat** [comment]
@apupier This was done deliberately. The SwitchYard projects were designed to be imported as Maven projects, not as Eclipse projects. So if you clone the git repo and import them as Maven projects it works fine.

**Comment by apupier** [comment]
@bfitzpat if we provide the Eclipse project metadata file, it will allow to provide more information and ease people to get started. We can configure Infiniti or MoreUnit for instance. There is a better integration of PDE also to import existing projects

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
will be covered by https://github.com/jboss-switchyard/tools/pull/625

**Pull request closed without merging**
