### PR TITLE
SWITCHYARD-2836 - neon - fixing the other half of the promote problem

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by apupier** [comment]
the commit name has the wrong number: 2386 instead of 2836

**Comment by bfitzpat** [comment]
Fixed commit title

**Comment by apupier** [comment]
+1 as it is the same commit bu ton another branch than https://github.com/jboss-switchyard/tools/pull/595

**Comment by bfitzpat** [comment]
@apupier or @lhein This is is an older PR that was approved prior to needing the "review" step in Github. Can one of you review/approve it (it's still necessary) so we can get this merged in and closed? 

Thanks!

**Pull request merged**
